// Copyright 2024 gorse Project Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: cache_store.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_cache_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Value) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Score struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	IsHidden      bool                   `protobuf:"varint,3,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	Categories    []string               `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Score) Reset() {
	*x = Score{}
	mi := &file_cache_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{1}
}

func (x *Score) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Score) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Score) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

func (x *Score) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Score) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ScoreCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subset        *string                `protobuf:"bytes,1,opt,name=subset,proto3,oneof" json:"subset,omitempty"`
	Id            *string                `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Before        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=before,proto3,oneof" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreCondition) Reset() {
	*x = ScoreCondition{}
	mi := &file_cache_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreCondition) ProtoMessage() {}

func (x *ScoreCondition) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreCondition.ProtoReflect.Descriptor instead.
func (*ScoreCondition) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{2}
}

func (x *ScoreCondition) GetSubset() string {
	if x != nil && x.Subset != nil {
		return *x.Subset
	}
	return ""
}

func (x *ScoreCondition) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ScoreCondition) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

type ScorePatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsHidden      *bool                  `protobuf:"varint,1,opt,name=is_hidden,json=isHidden,proto3,oneof" json:"is_hidden,omitempty"`
	Categories    []string               `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	Score         *float64               `protobuf:"fixed64,3,opt,name=score,proto3,oneof" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScorePatch) Reset() {
	*x = ScorePatch{}
	mi := &file_cache_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScorePatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScorePatch) ProtoMessage() {}

func (x *ScorePatch) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScorePatch.ProtoReflect.Descriptor instead.
func (*ScorePatch) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{3}
}

func (x *ScorePatch) GetIsHidden() bool {
	if x != nil && x.IsHidden != nil {
		return *x.IsHidden
	}
	return false
}

func (x *ScorePatch) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ScorePatch) GetScore() float64 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

type TimeSeriesPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeriesPoint) Reset() {
	*x = TimeSeriesPoint{}
	mi := &file_cache_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesPoint) ProtoMessage() {}

func (x *TimeSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesPoint.ProtoReflect.Descriptor instead.
func (*TimeSeriesPoint) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{4}
}

func (x *TimeSeriesPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TimeSeriesPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TimeSeriesPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_cache_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_cache_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{6}
}

func (x *GetResponse) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_cache_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{7}
}

func (x *SetRequest) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_cache_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{8}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_cache_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_cache_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{10}
}

type AddScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Subset        string                 `protobuf:"bytes,2,opt,name=subset,proto3" json:"subset,omitempty"`
	Documents     []*Score               `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddScoresRequest) Reset() {
	*x = AddScoresRequest{}
	mi := &file_cache_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddScoresRequest) ProtoMessage() {}

func (x *AddScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddScoresRequest.ProtoReflect.Descriptor instead.
func (*AddScoresRequest) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{11}
}

func (x *AddScoresRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *AddScoresRequest) GetSubset() string {
	if x != nil {
		return x.Subset
	}
	return ""
}

func (x *AddScoresRequest) GetDocuments() []*Score {
	if x != nil {
		return x.Documents
	}
	return nil
}

type AddScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddScoresResponse) Reset() {
	*x = AddScoresResponse{}
	mi := &file_cache_store_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddScoresResponse) ProtoMessage() {}

func (x *AddScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddScoresResponse.ProtoReflect.Descriptor instead.
func (*AddScoresResponse) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{12}
}

type GetScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Subset        string                 `protobuf:"bytes,2,opt,name=subset,proto3" json:"subset,omitempty"`
	Ids           []string               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoresRequest) Reset() {
	*x = GetScoresRequest{}
	mi := &file_cache_store_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoresRequest) ProtoMessage() {}

func (x *GetScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoresRequest.ProtoReflect.Descriptor instead.
func (*GetScoresRequest) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{13}
}

func (x *GetScoresRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetScoresRequest) GetSubset() string {
	if x != nil {
		return x.Subset
	}
	return ""
}

func (x *GetScoresRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Score               `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoresResponse) Reset() {
	*x = GetScoresResponse{}
	mi := &file_cache_store_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoresResponse) ProtoMessage() {}

func (x *GetScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoresResponse.ProtoReflect.Descriptor instead.
func (*GetScoresResponse) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{14}
}

func (x *GetScoresResponse) GetDocuments() []*Score {
	if x != nil {
		return x.Documents
	}
	return nil
}

type SearchScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Subset        string                 `protobuf:"bytes,2,opt,name=subset,proto3" json:"subset,omitempty"`
	Query         []string               `protobuf:"bytes,3,rep,name=query,proto3" json:"query,omitempty"`
	Begin         int32                  `protobuf:"varint,4,opt,name=begin,proto3" json:"begin,omitempty"`
	End           int32                  `protobuf:"varint,5,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchScoresRequest) Reset() {
	*x = SearchScoresRequest{}
	mi := &file_cache_store_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchScoresRequest) ProtoMessage() {}

func (x *SearchScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchScoresRequest.ProtoReflect.Descriptor instead.
func (*SearchScoresRequest) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{15}
}

func (x *SearchScoresRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchScoresRequest) GetSubset() string {
	if x != nil {
		return x.Subset
	}
	return ""
}

func (x *SearchScoresRequest) GetQuery() []string {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchScoresRequest) GetBegin() int32 {
	if x != nil {
		return x.Begin
	}
	return 0
}

func (x *SearchScoresRequest) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

type SearchScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Score               `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchScoresResponse) Reset() {
	*x = SearchScoresResponse{}
	mi := &file_cache_store_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchScoresResponse) ProtoMessage() {}

func (x *SearchScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchScoresResponse.ProtoReflect.Descriptor instead.
func (*SearchScoresResponse) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{16}
}

func (x *SearchScoresResponse) GetDocuments() []*Score {
	if x != nil {
		return x.Documents
	}
	return nil
}

type DeleteScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    []string               `protobuf:"bytes,1,rep,name=collection,proto3" json:"collection,omitempty"`
	Condition     *ScoreCondition        `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScoresRequest) Reset() {
	*x = DeleteScoresRequest{}
	mi := &file_cache_store_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScoresRequest) ProtoMessage() {}

func (x *DeleteScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScoresRequest.ProtoReflect.Descriptor instead.
func (*DeleteScoresRequest) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteScoresRequest) GetCollection() []string {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *DeleteScoresRequest) GetCondition() *ScoreCondition {
	if x != nil {
		return x.Condition
	}
	return nil
}

type DeleteScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScoresResponse) Reset() {
	*x = DeleteScoresResponse{}
	mi := &file_cache_store_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScoresResponse) ProtoMessage() {}

func (x *DeleteScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScoresResponse.ProtoReflect.Descriptor instead.
func (*DeleteScoresResponse) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{18}
}

type UpdateScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    []string               `protobuf:"bytes,1,rep,name=collection,proto3" json:"collection,omitempty"`
	Subset        *string                `protobuf:"bytes,2,opt,name=subset,proto3,oneof" json:"subset,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Patch         *ScorePatch            `protobuf:"bytes,4,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScoresRequest) Reset() {
	*x = UpdateScoresRequest{}
	mi := &file_cache_store_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoresRequest) ProtoMessage() {}

func (x *UpdateScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoresRequest.ProtoReflect.Descriptor instead.
func (*UpdateScoresRequest) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateScoresRequest) GetCollection() []string {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *UpdateScoresRequest) GetSubset() string {
	if x != nil && x.Subset != nil {
		return *x.Subset
	}
	return ""
}

func (x *UpdateScoresRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateScoresRequest) GetPatch() *ScorePatch {
	if x != nil {
		return x.Patch
	}
	return nil
}

type UpdateScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScoresResponse) Reset() {
	*x = UpdateScoresResponse{}
	mi := &file_cache_store_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoresResponse) ProtoMessage() {}

func (x *UpdateScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoresResponse.ProtoReflect.Descriptor instead.
func (*UpdateScoresResponse) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{20}
}

type ScanScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanScoresRequest) Reset() {
	*x = ScanScoresRequest{}
	mi := &file_cache_store_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanScoresRequest) ProtoMessage() {}

func (x *ScanScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanScoresRequest.ProtoReflect.Descriptor instead.
func (*ScanScoresRequest) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{21}
}

type ScanScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Subset        string                 `protobuf:"bytes,3,opt,name=subset,proto3" json:"subset,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanScoresResponse) Reset() {
	*x = ScanScoresResponse{}
	mi := &file_cache_store_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanScoresResponse) ProtoMessage() {}

func (x *ScanScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanScoresResponse.ProtoReflect.Descriptor instead.
func (*ScanScoresResponse) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{22}
}

func (x *ScanScoresResponse) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *ScanScoresResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScanScoresResponse) GetSubset() string {
	if x != nil {
		return x.Subset
	}
	return ""
}

func (x *ScanScoresResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type AddTimeSeriesPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*TimeSeriesPoint     `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTimeSeriesPointsRequest) Reset() {
	*x = AddTimeSeriesPointsRequest{}
	mi := &file_cache_store_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTimeSeriesPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTimeSeriesPointsRequest) ProtoMessage() {}

func (x *AddTimeSeriesPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTimeSeriesPointsRequest.ProtoReflect.Descriptor instead.
func (*AddTimeSeriesPointsRequest) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{23}
}

func (x *AddTimeSeriesPointsRequest) GetPoints() []*TimeSeriesPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type AddTimeSeriesPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTimeSeriesPointsResponse) Reset() {
	*x = AddTimeSeriesPointsResponse{}
	mi := &file_cache_store_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTimeSeriesPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTimeSeriesPointsResponse) ProtoMessage() {}

func (x *AddTimeSeriesPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTimeSeriesPointsResponse.ProtoReflect.Descriptor instead.
func (*AddTimeSeriesPointsResponse) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{24}
}

type GetTimeSeriesPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Begin         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=begin,proto3" json:"begin,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Duration      int64                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimeSeriesPointsRequest) Reset() {
	*x = GetTimeSeriesPointsRequest{}
	mi := &file_cache_store_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimeSeriesPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeSeriesPointsRequest) ProtoMessage() {}

func (x *GetTimeSeriesPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeSeriesPointsRequest.ProtoReflect.Descriptor instead.
func (*GetTimeSeriesPointsRequest) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{25}
}

func (x *GetTimeSeriesPointsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTimeSeriesPointsRequest) GetBegin() *timestamppb.Timestamp {
	if x != nil {
		return x.Begin
	}
	return nil
}

func (x *GetTimeSeriesPointsRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *GetTimeSeriesPointsRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type GetTimeSeriesPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*TimeSeriesPoint     `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimeSeriesPointsResponse) Reset() {
	*x = GetTimeSeriesPointsResponse{}
	mi := &file_cache_store_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimeSeriesPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeSeriesPointsResponse) ProtoMessage() {}

func (x *GetTimeSeriesPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_store_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeSeriesPointsResponse.ProtoReflect.Descriptor instead.
func (*GetTimeSeriesPointsResponse) Descriptor() ([]byte, []int) {
	return file_cache_store_proto_rawDescGZIP(), []int{26}
}

func (x *GetTimeSeriesPointsResponse) GetPoints() []*TimeSeriesPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_cache_store_proto protoreflect.FileDescriptor

const file_cache_store_proto_rawDesc = "" +
	"\n" +
	"\x11cache_store.proto\x12\bprotocol\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0eprotocol.proto\"1\n" +
	"\x05Value\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xa4\x01\n" +
	"\x05Score\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x1b\n" +
	"\tis_hidden\x18\x03 \x01(\bR\bisHidden\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x98\x01\n" +
	"\x0eScoreCondition\x12\x1b\n" +
	"\x06subset\x18\x01 \x01(\tH\x00R\x06subset\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tH\x01R\x02id\x88\x01\x01\x127\n" +
	"\x06before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x06before\x88\x01\x01B\t\n" +
	"\a_subsetB\x05\n" +
	"\x03_idB\t\n" +
	"\a_before\"\x81\x01\n" +
	"\n" +
	"ScorePatch\x12 \n" +
	"\tis_hidden\x18\x01 \x01(\bH\x00R\bisHidden\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"categories\x18\x02 \x03(\tR\n" +
	"categories\x12\x19\n" +
	"\x05score\x18\x03 \x01(\x01H\x01R\x05score\x88\x01\x01B\f\n" +
	"\n" +
	"_is_hiddenB\b\n" +
	"\x06_score\"u\n" +
	"\x0fTimeSeriesPoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"2\n" +
	"\vGetResponse\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"5\n" +
	"\n" +
	"SetRequest\x12'\n" +
	"\x06values\x18\x01 \x03(\v2\x0f.protocol.ValueR\x06values\"\r\n" +
	"\vSetResponse\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x10\n" +
	"\x0eDeleteResponse\"y\n" +
	"\x10AddScoresRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x16\n" +
	"\x06subset\x18\x02 \x01(\tR\x06subset\x12-\n" +
	"\tdocuments\x18\x03 \x03(\v2\x0f.protocol.ScoreR\tdocuments\"\x13\n" +
	"\x11AddScoresResponse\"\\\n" +
	"\x10GetScoresRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x16\n" +
	"\x06subset\x18\x02 \x01(\tR\x06subset\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\"B\n" +
	"\x11GetScoresResponse\x12-\n" +
	"\tdocuments\x18\x01 \x03(\v2\x0f.protocol.ScoreR\tdocuments\"\x8b\x01\n" +
	"\x13SearchScoresRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x16\n" +
	"\x06subset\x18\x02 \x01(\tR\x06subset\x12\x14\n" +
	"\x05query\x18\x03 \x03(\tR\x05query\x12\x14\n" +
	"\x05begin\x18\x04 \x01(\x05R\x05begin\x12\x10\n" +
	"\x03end\x18\x05 \x01(\x05R\x03end\"E\n" +
	"\x14SearchScoresResponse\x12-\n" +
	"\tdocuments\x18\x01 \x03(\v2\x0f.protocol.ScoreR\tdocuments\"m\n" +
	"\x13DeleteScoresRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x03(\tR\n" +
	"collection\x126\n" +
	"\tcondition\x18\x02 \x01(\v2\x18.protocol.ScoreConditionR\tcondition\"\x16\n" +
	"\x14DeleteScoresResponse\"\x99\x01\n" +
	"\x13UpdateScoresRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x03(\tR\n" +
	"collection\x12\x1b\n" +
	"\x06subset\x18\x02 \x01(\tH\x00R\x06subset\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12*\n" +
	"\x05patch\x18\x04 \x01(\v2\x14.protocol.ScorePatchR\x05patchB\t\n" +
	"\a_subset\"\x16\n" +
	"\x14UpdateScoresResponse\"\x13\n" +
	"\x11ScanScoresRequest\"\x96\x01\n" +
	"\x12ScanScoresResponse\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06subset\x18\x03 \x01(\tR\x06subset\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"O\n" +
	"\x1aAddTimeSeriesPointsRequest\x121\n" +
	"\x06points\x18\x01 \x03(\v2\x19.protocol.TimeSeriesPointR\x06points\"\x1d\n" +
	"\x1bAddTimeSeriesPointsResponse\"\xac\x01\n" +
	"\x1aGetTimeSeriesPointsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x05begin\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05begin\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x03R\bduration\"P\n" +
	"\x1bGetTimeSeriesPointsResponse\x121\n" +
	"\x06points\x18\x01 \x03(\v2\x19.protocol.TimeSeriesPointR\x06points2\x8c\a\n" +
	"\n" +
	"CacheStore\x127\n" +
	"\x04Ping\x12\x15.protocol.PingRequest\x1a\x16.protocol.PingResponse\"\x00\x124\n" +
	"\x03Get\x12\x14.protocol.GetRequest\x1a\x15.protocol.GetResponse\"\x00\x124\n" +
	"\x03Set\x12\x14.protocol.SetRequest\x1a\x15.protocol.SetResponse\"\x00\x12=\n" +
	"\x06Delete\x12\x17.protocol.DeleteRequest\x1a\x18.protocol.DeleteResponse\"\x00\x12F\n" +
	"\tAddScores\x12\x1a.protocol.AddScoresRequest\x1a\x1b.protocol.AddScoresResponse\"\x00\x12F\n" +
	"\tGetScores\x12\x1a.protocol.GetScoresRequest\x1a\x1b.protocol.GetScoresResponse\"\x00\x12O\n" +
	"\fSearchScores\x12\x1d.protocol.SearchScoresRequest\x1a\x1e.protocol.SearchScoresResponse\"\x00\x12O\n" +
	"\fDeleteScores\x12\x1d.protocol.DeleteScoresRequest\x1a\x1e.protocol.DeleteScoresResponse\"\x00\x12O\n" +
	"\fUpdateScores\x12\x1d.protocol.UpdateScoresRequest\x1a\x1e.protocol.UpdateScoresResponse\"\x00\x12K\n" +
	"\n" +
	"ScanScores\x12\x1b.protocol.ScanScoresRequest\x1a\x1c.protocol.ScanScoresResponse\"\x000\x01\x12d\n" +
	"\x13AddTimeSeriesPoints\x12$.protocol.AddTimeSeriesPointsRequest\x1a%.protocol.AddTimeSeriesPointsResponse\"\x00\x12d\n" +
	"\x13GetTimeSeriesPoints\x12$.protocol.GetTimeSeriesPointsRequest\x1a%.protocol.GetTimeSeriesPointsResponse\"\x00B$Z\"github.com/gorse-io/gorse/protocolb\x06proto3"

var (
	file_cache_store_proto_rawDescOnce sync.Once
	file_cache_store_proto_rawDescData []byte
)

func file_cache_store_proto_rawDescGZIP() []byte {
	file_cache_store_proto_rawDescOnce.Do(func() {
		file_cache_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_store_proto_rawDesc), len(file_cache_store_proto_rawDesc)))
	})
	return file_cache_store_proto_rawDescData
}

var file_cache_store_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_cache_store_proto_goTypes = []any{
	(*Value)(nil),                       // 0: protocol.Value
	(*Score)(nil),                       // 1: protocol.Score
	(*ScoreCondition)(nil),              // 2: protocol.ScoreCondition
	(*ScorePatch)(nil),                  // 3: protocol.ScorePatch
	(*TimeSeriesPoint)(nil),             // 4: protocol.TimeSeriesPoint
	(*GetRequest)(nil),                  // 5: protocol.GetRequest
	(*GetResponse)(nil),                 // 6: protocol.GetResponse
	(*SetRequest)(nil),                  // 7: protocol.SetRequest
	(*SetResponse)(nil),                 // 8: protocol.SetResponse
	(*DeleteRequest)(nil),               // 9: protocol.DeleteRequest
	(*DeleteResponse)(nil),              // 10: protocol.DeleteResponse
	(*AddScoresRequest)(nil),            // 11: protocol.AddScoresRequest
	(*AddScoresResponse)(nil),           // 12: protocol.AddScoresResponse
	(*GetScoresRequest)(nil),            // 13: protocol.GetScoresRequest
	(*GetScoresResponse)(nil),           // 14: protocol.GetScoresResponse
	(*SearchScoresRequest)(nil),         // 15: protocol.SearchScoresRequest
	(*SearchScoresResponse)(nil),        // 16: protocol.SearchScoresResponse
	(*DeleteScoresRequest)(nil),         // 17: protocol.DeleteScoresRequest
	(*DeleteScoresResponse)(nil),        // 18: protocol.DeleteScoresResponse
	(*UpdateScoresRequest)(nil),         // 19: protocol.UpdateScoresRequest
	(*UpdateScoresResponse)(nil),        // 20: protocol.UpdateScoresResponse
	(*ScanScoresRequest)(nil),           // 21: protocol.ScanScoresRequest
	(*ScanScoresResponse)(nil),          // 22: protocol.ScanScoresResponse
	(*AddTimeSeriesPointsRequest)(nil),  // 23: protocol.AddTimeSeriesPointsRequest
	(*AddTimeSeriesPointsResponse)(nil), // 24: protocol.AddTimeSeriesPointsResponse
	(*GetTimeSeriesPointsRequest)(nil),  // 25: protocol.GetTimeSeriesPointsRequest
	(*GetTimeSeriesPointsResponse)(nil), // 26: protocol.GetTimeSeriesPointsResponse
	(*timestamppb.Timestamp)(nil),       // 27: google.protobuf.Timestamp
	(*PingRequest)(nil),                 // 28: protocol.PingRequest
	(*PingResponse)(nil),                // 29: protocol.PingResponse
}
var file_cache_store_proto_depIdxs = []int32{
	27, // 0: protocol.Score.timestamp:type_name -> google.protobuf.Timestamp
	27, // 1: protocol.ScoreCondition.before:type_name -> google.protobuf.Timestamp
	27, // 2: protocol.TimeSeriesPoint.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 3: protocol.SetRequest.values:type_name -> protocol.Value
	1,  // 4: protocol.AddScoresRequest.documents:type_name -> protocol.Score
	1,  // 5: protocol.GetScoresResponse.documents:type_name -> protocol.Score
	1,  // 6: protocol.SearchScoresResponse.documents:type_name -> protocol.Score
	2,  // 7: protocol.DeleteScoresRequest.condition:type_name -> protocol.ScoreCondition
	3,  // 8: protocol.UpdateScoresRequest.patch:type_name -> protocol.ScorePatch
	27, // 9: protocol.ScanScoresResponse.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 10: protocol.AddTimeSeriesPointsRequest.points:type_name -> protocol.TimeSeriesPoint
	27, // 11: protocol.GetTimeSeriesPointsRequest.begin:type_name -> google.protobuf.Timestamp
	27, // 12: protocol.GetTimeSeriesPointsRequest.end:type_name -> google.protobuf.Timestamp
	4,  // 13: protocol.GetTimeSeriesPointsResponse.points:type_name -> protocol.TimeSeriesPoint
	28, // 14: protocol.CacheStore.Ping:input_type -> protocol.PingRequest
	5,  // 15: protocol.CacheStore.Get:input_type -> protocol.GetRequest
	7,  // 16: protocol.CacheStore.Set:input_type -> protocol.SetRequest
	9,  // 17: protocol.CacheStore.Delete:input_type -> protocol.DeleteRequest
	11, // 18: protocol.CacheStore.AddScores:input_type -> protocol.AddScoresRequest
	13, // 19: protocol.CacheStore.GetScores:input_type -> protocol.GetScoresRequest
	15, // 20: protocol.CacheStore.SearchScores:input_type -> protocol.SearchScoresRequest
	17, // 21: protocol.CacheStore.DeleteScores:input_type -> protocol.DeleteScoresRequest
	19, // 22: protocol.CacheStore.UpdateScores:input_type -> protocol.UpdateScoresRequest
	21, // 23: protocol.CacheStore.ScanScores:input_type -> protocol.ScanScoresRequest
	23, // 24: protocol.CacheStore.AddTimeSeriesPoints:input_type -> protocol.AddTimeSeriesPointsRequest
	25, // 25: protocol.CacheStore.GetTimeSeriesPoints:input_type -> protocol.GetTimeSeriesPointsRequest
	29, // 26: protocol.CacheStore.Ping:output_type -> protocol.PingResponse
	6,  // 27: protocol.CacheStore.Get:output_type -> protocol.GetResponse
	8,  // 28: protocol.CacheStore.Set:output_type -> protocol.SetResponse
	10, // 29: protocol.CacheStore.Delete:output_type -> protocol.DeleteResponse
	12, // 30: protocol.CacheStore.AddScores:output_type -> protocol.AddScoresResponse
	14, // 31: protocol.CacheStore.GetScores:output_type -> protocol.GetScoresResponse
	16, // 32: protocol.CacheStore.SearchScores:output_type -> protocol.SearchScoresResponse
	18, // 33: protocol.CacheStore.DeleteScores:output_type -> protocol.DeleteScoresResponse
	20, // 34: protocol.CacheStore.UpdateScores:output_type -> protocol.UpdateScoresResponse
	22, // 35: protocol.CacheStore.ScanScores:output_type -> protocol.ScanScoresResponse
	24, // 36: protocol.CacheStore.AddTimeSeriesPoints:output_type -> protocol.AddTimeSeriesPointsResponse
	26, // 37: protocol.CacheStore.GetTimeSeriesPoints:output_type -> protocol.GetTimeSeriesPointsResponse
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_cache_store_proto_init() }
func file_cache_store_proto_init() {
	if File_cache_store_proto != nil {
		return
	}
	file_protocol_proto_init()
	file_cache_store_proto_msgTypes[2].OneofWrappers = []any{}
	file_cache_store_proto_msgTypes[3].OneofWrappers = []any{}
	file_cache_store_proto_msgTypes[6].OneofWrappers = []any{}
	file_cache_store_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_store_proto_rawDesc), len(file_cache_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_store_proto_goTypes,
		DependencyIndexes: file_cache_store_proto_depIdxs,
		MessageInfos:      file_cache_store_proto_msgTypes,
	}.Build()
	File_cache_store_proto = out.File
	file_cache_store_proto_goTypes = nil
	file_cache_store_proto_depIdxs = nil
}
